name: mk_bio
description: Biometrics app for MK GROUP
version: 0.1.4

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_redux: ^0.5.3
  image_picker: ^0.6.0+10
  json_serializable: ^3.2.0
  fluttertoast:
  path_provider:
  path:
  camera:
  rect_getter:
  dotted_border:
  image_gallery_saver:
  meta:
  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git



dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "images/Logo.png"

flutter:
  uses-material-design: true
  assets:
    - images/lake.jpg
    - images/beautiful-color-gradients-backgrounds-047-fly-high.png
    - images/Logo.png
